### PR TITLE
store single image url

### PR DESCRIPTION
**Pull request by maksz42**
There are 3 sizes of the same photo. No need to store 3 URLs. Reduces JSON size by 10%.

### CODE REVIEW

**Review by yaqwsx — APPROVED** [review]

**Comment by yaqwsx** [comment]
Thanks you for the contribution.

**Comment by maksz42** [comment]
Btw, I don't know if you did something or mozilla did but it works much faster on firefox recently, especially the catalogue update is like 3x faster.

**Comment by yaqwsx** [comment]
There was only a single change since I relaunched the service - we don't store components that have been out of stock for more than six months. This shrinks down the database roughly to 1/3 of the original size.

**Comment by yaqwsx** [comment]
Once we migrate to a better DB, I plan to serve all components again. But until that happens, this makes the service much more useful.

**Pull request merged**
